FROM node:16

# Create app directory
WORKDIR /home/openbackhaul/Accessport2LtpTranslator

# Install and app dependencies
# A wildcard is used to ensure both package.json AND package-lock.json are copied
COPY package*.json ./

# install application by NPM
RUN npm ci --only=production

# Bundle app source
COPY . .

EXPOSE 4003

#Command to start the application
CMD [ "node", "index.js" ]
