openapi: 3.0.0
info:
  title: Acessport2LtpTranslator
  version: 1.0.0

paths:
  /alap-beispiel:
    post:
      operationId: provideAcceptanceDataOfLinkEndpoint
      summary: 'Provides the data required for the acceptance of a device'
      tags:
        - IndividualServices
      security:
        - basicAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - mount-name
                - link-id
              properties:
                mount-name:
                  type: string
                  description: 'Identifier of the device at the Controller'
                link-id:
                  type: string
                  description: 'Identifier of the microwave link in the Telefonica planing tools'
              example:
                mount-name: '513250010'
                link-id: '513550010'
      responses:
        '200':
          description: 'Data for device acceptance provided'
          content:
            application/json:
              schema:
                type: object
                properties:
                  air-interface:
                    type: object
                    properties:
                      configured-adaptive-modulation-is-on:
                        type: boolean
                        description: >
                          'This configuration value is true, if adpative modulation is configured to be switched on
                          from {$RequestForProvidingAcceptanceDataCausesReadingConfigurationFromCache.ConfigurationFromCache.response.body#air-interface-2-0:air-interface-configuration/adaptive-modulation-is-on}'
                      configured-modulation-minimum:
                        type: object
                        description: 'Configured minimum modulation scheme'
                        properties:
                          number-of-states:
                            type: integer
                            description: >
                              'Number of states in the phase diagram (e.g. BPSK->2 or 256QAM->256)
                              transmissionModeMin = {$RequestForProvidingAcceptanceDataCausesReadingConfigurationFromCache.ConfigurationFromCache.response.body#air-interface-2-0:air-interface-configuration/transmission-mode-min}
                              from {$RequestForProvidingAcceptanceDataCausesReadingCapabilitiesFromCache.CapabilitiesFromCache.response.body#air-interface-2-0:air-interface-capability/transmission-mode-list/modulation-scheme}
                              where {$RequestForProvidingAcceptanceDataCausesReadingCapabilitiesFromCache.CapabilitiesFromCache.response.body#air-interface-2-0:air-interface-capability/transmission-mode-list/transmission-mode-name} == transmissionModeMin'
                          name-at-lct:
                            type: string
                            description: >
                              'Name identifying this transmission mode on the graphical user interface of the local craft terminal
                              transmissionModeMin = {$RequestForProvidingAcceptanceDataCausesReadingConfigurationFromCache.ConfigurationFromCache.response.body#air-interface-2-0:air-interface-configuration/transmission-mode-min}
                              from {$RequestForProvidingAcceptanceDataCausesReadingCapabilitiesFromCache.CapabilitiesFromCache.response.body#air-interface-2-0:air-interface-capability/transmission-mode-list/modulation-scheme-name-at-lct}
                              where {$RequestForProvidingAcceptanceDataCausesReadingCapabilitiesFromCache.CapabilitiesFromCache.response.body#air-interface-2-0:air-interface-capability/transmission-mode-list/transmission-mode-name} == transmissionModeMin'
                  vlan-interface:
                    type: object
                    properties:
                      configured-lan-port-role-list:
                        description: 'Provided for Ericsson devices only'
                        type: array
                        items:
                          type: object
                          properties:
                            interface-name:
                              type: string
                              description: >
                                'Interface name of the EthernetContainer as it is represented at the vendors own management interface
                                The List of LTPs from RequestForProvidingAcceptanceDataCausesReadingLtpStructure has to be filtered for LayerProtocolName == WireLayer
                                Starting from each WireInterfaceLtp the client EthernetContainerLtp have to be identified by
                                ClientStructureUuid = WireInterface.ClientLtp
                                ClientContainerUuid = ClientStructure.ClientLtp
                                Based on the ClientContainerUuid the interface-name has to be retrieved
                                from {$RequestForProvidingAcceptanceDataCausesDeterminingTheLanPortRole.OriginalLtpName.response.body#ltp-augment-1-0:ltp-augment-pac/original-ltp-name'
                            vlan-interface-kind:
                              type: string
                              description: >
                                'Categorizes the interface according to its characteristics on the VLAN layer
                                Starting from each EthernetContainerLtp the client VlanInterfaceLtp have to be identified by
                                ClientMacInterfaceUuid = ClientContainer.ClientLtp
                                ClientVlanInterfaceUuid = ClientMacInterface.ClientLtp
                                Based on the ClientVlanInterfaceUuid the vlan-interface-kind has to be retrieved
                                from {$RequestForProvidingAcceptanceDataCausesDeterminingTheLanPortRole.VlanInterfaceKind.response.body#vlan-interface-1-0:vlan-interface-configuration/interface-kind'
                            serving-ethernet-container-status:
                              type: string
                              description: >
                                'Status of the EthernetContainer that is beneath the VLAN interface
                                Based on the ClientContainerUuid the interface-status has to be retrieved
                                from {$RequestForProvidingAcceptanceDataCausesDeterminingTheLanPortRole.EthernetContainerStatus.response.body#ethernet-container-2-0:ethernet-container-status/interface-status'
                  inventory:
                    type: object
                    properties:
                      radio:
                        type: object
                        properties:
                          equipment-name:
                            type: string
                            description: >
                              'Name of the radio type
                              if {$RequestForProvidingAcceptanceDataCausesReadingTheRadioComponentIdentifiers.EquipmentInfo.response.body#core-model-1-4:actual-equipment/structure/category} == equipment-augment-1-0:EQUIPMENT_CATEGORY_OUTDOOR_UNIT
                              from {$RequestForProvidingAcceptanceDataCausesReadingTheRadioComponentIdentifiers.EquipmentInfo.response.body#core-model-1-4:actual-equipment/manufactured-thing/equipment-type/type-name}'
 

  parameters:
    user:
      name: user
      in: header
      required: true
      schema:
        type: string
        example: 'User Name'
      description: 'User identifier from the system starting the service call'
    originator:
      name: originator
      in: header
      required: true
      schema:
        type: string
        minLength: 3
        example: 'Resolver'
      description: >
        'Identification for the system consuming the API, as defined in
         [/core-model-1-4:control-construct/logical-termination-point={uuid}/layer-protocol=0/http-client-interface-1-0:http-client-interface-pac/http-client-interface-configuration/application-name]'
    x-correlator:
      name: x-correlator
      in: header
      required: true
      schema:
        type: string
        pattern: '^[0-9A-Fa-f]{8}(?:-[0-9A-Fa-f]{4}){3}-[0-9A-Fa-f]{12}$'
        description: 'Empty string accepted from external applications.'
        example: '550e8400-e29b-11d4-a716-446655440000'
      description: 'UUID for the service execution flow that allows to correlate requests and responses'
    trace-indicator:
      name: trace-indicator
      in: header
      required: true
      schema:
        type: string
        pattern: '^([0-9]+)(\.([0-9]+))*$'
        description: 'Empty string accepted from external applications.'
        example: '1.3.1'
      description: 'Sequence of request numbers along the flow'
    customer-journey:
      name: customer-journey
      in: header
      required: true
      schema:
        type: string
        example: 'Unknown value'
      description: 'Holds information supporting customer’s journey to which the execution applies'
  responses:
    responseForErroredServiceRequests:
      description: 'Response in case of errored service requests'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/errorDescription'
      headers:
        x-correlator:
          schema:
            type: string
            pattern: '^[0-9A-Fa-f]{8}(?:-[0-9A-Fa-f]{4}){3}-[0-9A-Fa-f]{12}$'
            example: '550e8400-e29b-11d4-a716-446655440000'
          description: 'UUID for the service execution flow that allows to correlate requests and responses. Its value must be identical at the response compared with its corresponding request'
        exec-time:
          schema:
            type: integer
            example: 1100
          description: 'Value written by the service provider, reporting the total elapsed time for the execution, including all the additional processing needed to retrieve the data from the backend service. Expressed in milliseconds'
        backend-time:
          schema:
            type: integer
            example: 850
          description: 'Value written by the service provider, reporting the elapsed time for data retrieval from the backend (service invocation, database access…). Expressed in milliseconds'
    responseForErroredOamRequests:
      description: 'Response in case of errored OaM requests'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/errorDescription'
  schemas:
    errorDescription:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
  securitySchemes:
    apiKeyAuth:
      type: apiKey
      in: header
      name: operation-key
    basicAuth:
      type: http
      scheme: basic