@startuml 01x_translate-equipment-to-ltp
skinparam responseMessageBelowArrow true

title Provide LTP for Equipment

participant "A2LT://v1/translate-equipment-to-ltp"
participant "MWDI://...control-construct?top-level-equipment"
participant "MWDI://...control-construct/equipment={uuid}"
participant "MWDI://...control-construct/logical-termination-point={uuid}"

[-> "A2LT://v1/translate-equipment-to-ltp": {device,sequence-id-string}(apiKeyAuth)



"A2LT://v1/translate-equipment-to-ltp"-->"MWDI://...control-construct?top-level-equipment": {MountName}
"A2LT://v1/translate-equipment-to-ltp"<--"MWDI://...control-construct?top-level-equipment": {equipment=uuid}
"A2LT://v1/translate-equipment-to-ltp"-->"MWDI://...control-construct/equipment={uuid}": {uuid}
"A2LT://v1/translate-equipment-to-ltp"<--"MWDI://...control-construct/equipment={uuid}": {control-construct/equipment{}}
"A2LT://v1/translate-equipment-to-ltp"-->"MWDI://...control-construct/logical-termination-point={uuid}": {local-id}
"A2LT://v1/translate-equipment-to-ltp"<--"MWDI://...control-construct/logical-termination-point={uuid}": {logical-termination-point=uuid}

[<- "A2LT://v1/translate-equipment-to-ltp": {[{uuid,client-ltp,server-ltp,layer-protocol-name}]}

@enduml